# Generated by Django 6.0.6 on 2026-06-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], db_index=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_sizes', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='shoes/')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='products_sh_categor_3c642e_idx'), models.Index(fields=['brand'], name='products_sh_brand_89f979_idx')],
            },
        ),
    ]
